[package]
name = "rust-image-server"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.7", features = ["multipart", "ws"] }
image = "0.25.10"
mime_guess = "2.0.5"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
tokio = { version = "1.0", features = ["full"] }
tower = { version = "0.5.3", features = ["limit"] }
tower-http = { version = "0.5", features = ["fs"] }
# Add sqlx dependencies
sqlx = { version = "0.8", features = ["runtime-tokio", "sqlite", "macros"] }
dotenvy = "0.15"
exif = { package = "kamadak-exif", version = "0.6" }
actix-web = "4.13.0"
rexif = "0.7"

